# ─────────────────────────────────────────────────────────────────────────────
# Stage 1 — deps: install ALL dependencies (dev+prod needed for next build)
# ─────────────────────────────────────────────────────────────────────────────
FROM node:20-alpine AS deps

RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy manifests only — maximises layer cache
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile


# ─────────────────────────────────────────────────────────────────────────────
# Stage 2 — builder: run `next build` → produces .next/standalone
# ─────────────────────────────────────────────────────────────────────────────
FROM node:20-alpine AS builder

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build-time public env var — baked into the client bundle
ARG NEXT_PUBLIC_API_URL=http://localhost:4000
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_TELEMETRY_DISABLED=1

# next.config.ts has output:"standalone" → emits .next/standalone
RUN yarn build


# ─────────────────────────────────────────────────────────────────────────────
# Stage 3 — runner: minimal image using ONLY the standalone bundle
#
# output:"standalone" makes Next.js produce:
#   .next/standalone/        ← complete server (node_modules already inlined)
#   .next/static/            ← client-side assets
#   public/                  ← static public files
#
# We do NOT need to copy node_modules here — they are already bundled inside
# .next/standalone/node_modules by Next.js itself.
# ─────────────────────────────────────────────────────────────────────────────
FROM node:20-alpine AS runner

LABEL maintainer="fyneo"
LABEL description="Fyneo Next.js 16 frontend (standalone)"

RUN apk add --no-cache libc6-compat

# Non-root user for security
RUN addgroup --system --gid 1001 nextjs \
 && adduser  --system --uid 1001 --ingroup nextjs nextjs

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# ── Copy only what the standalone server needs ────────────────────────────────
# Use --chown on each COPY — avoids the very expensive `chown -R` on the
# entire node_modules tree which caused the I/O errors in the previous build.
COPY --from=builder --chown=nextjs:nextjs /app/public            ./public
COPY --from=builder --chown=nextjs:nextjs /app/.next/standalone  ./
COPY --from=builder --chown=nextjs:nextjs /app/.next/static      ./.next/static

USER nextjs

EXPOSE 3000

# server.js is generated by Next.js standalone output
CMD ["node", "server.js"]
