# ─────────────────────────────────────────────────────────────────────────────
# Fyneo — Next.js 16 Frontend
# Multi-stage build using output:"standalone" for minimal production image.
#
# Key decisions:
#  - node:22-alpine  → required by camera-controls@3.1.2 (Node >=22)
#  - .yarnrc         → sets network-timeout + ignore-optional globally
#                      (skips @next/swc-* 50MB native binaries that time-out)
#  - output:standalone → runner stage copies ONLY 3 dirs, no node_modules
#  - --chown on COPY  → avoids expensive `chown -R` that causes I/O errors
# ─────────────────────────────────────────────────────────────────────────────

# ── Stage 1 · deps ────────────────────────────────────────────────────────────
FROM node:22-alpine AS deps

RUN apk add --no-cache libc6-compat

WORKDIR /app

# .yarnrc is copied first — it configures network-timeout, ignore-optional,
# and ignore-engines before yarn install runs.
COPY .yarnrc       ./
COPY package.json  yarn.lock ./

# The CI overlay2 filesystem has I/O errors on /tmp (different layer).
# Using /app/.yarn-cache (same layer as node_modules) avoids this.
RUN mkdir -p /app/.yarn-cache && \
    yarn install \
      --ignore-optional \
      --ignore-engines \
      --force \
      --network-timeout 300000 \
      --cache-folder /app/.yarn-cache && \
    rm -rf /app/.yarn-cache


# ── Stage 2 · builder ─────────────────────────────────────────────────────────
FROM node:22-alpine AS builder

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# NEXT_PUBLIC_API_URL is baked into the JS bundle at build time.
# The browser uses this value to reach the backend API.
# Set this build-arg in your platform to the REAL backend URL —
# "localhost" only works on the developer's machine, not in production.
#
# Example: docker build --build-arg NEXT_PUBLIC_API_URL=https://api.fyneo.io .
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_TELEMETRY_DISABLED=1

# next.config.ts: output:"standalone" → .next/standalone/ (self-contained)
RUN yarn build


# ── Stage 3 · runner ──────────────────────────────────────────────────────────
FROM node:22-alpine AS runner

LABEL maintainer="fyneo"
LABEL description="Fyneo Next.js 16 frontend"

RUN apk add --no-cache libc6-compat

RUN addgroup --system --gid 1001 nextjs \
 && adduser  --system --uid 1001 --ingroup nextjs nextjs

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Copy ONLY the 3 standalone artefacts — no node_modules needed here.
# next build with output:"standalone" bundles everything into .next/standalone/.
# Using --chown per-COPY avoids running chown -R on thousands of files.
COPY --from=builder --chown=nextjs:nextjs /app/public           ./public
COPY --from=builder --chown=nextjs:nextjs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nextjs /app/.next/static     ./.next/static

USER nextjs

EXPOSE 3000

# server.js is auto-generated by Next.js inside .next/standalone/
CMD ["node", "server.js"]
