# ─────────────────────────────────────────────────────────────────────────────
# Stage 1 — deps: install all dependencies
# ─────────────────────────────────────────────────────────────────────────────
FROM node:22-alpine AS deps

# Required for some native modules (sharp, canvas, etc.)
RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json yarn.lock ./

# Install all deps (devDeps needed for next build)
RUN yarn install --frozen-lockfile


# ─────────────────────────────────────────────────────────────────────────────
# Stage 2 — builder: compile/export the Next.js application
# ─────────────────────────────────────────────────────────────────────────────
FROM node:22-alpine AS builder

RUN apk add --no-cache libc6-compat

WORKDIR /app

# Carry in node_modules from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy entire source tree
COPY . .

# ── Build-time public env vars ────────────────────────────────────────────────
# These are embedded into the client bundle at build time by Next.js.
# Pass them with --build-arg or set them in your CI pipeline / docker-compose.
# Example:  docker build --build-arg NEXT_PUBLIC_API_URL=https://api.fyneo.io .
ARG NEXT_PUBLIC_API_URL=http://localhost:4000
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

# Disable Next.js telemetry
ENV NEXT_TELEMETRY_DISABLED=1

# Produce a standalone output bundle → minimal runtime footprint
# (requires next.config output: 'standalone' — handled by next-config env below)
RUN yarn build


# ─────────────────────────────────────────────────────────────────────────────
# Stage 3 — runner: lean production image
# ─────────────────────────────────────────────────────────────────────────────
FROM node:22-alpine AS runner

LABEL maintainer="fyneo"
LABEL description="Fyneo Next.js frontend"

RUN apk add --no-cache libc6-compat

# Non-root user
RUN addgroup --system --gid 1001 nextjs \
 && adduser  --system --uid 1001 --ingroup nextjs nextjs

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# ─── Copy standalone output (generated by next build with output:'standalone') ─
# If output:'standalone' is NOT set in next.config.ts, fall back to copying
# .next, public, node_modules and package.json manually.
#
# We support BOTH approaches below — the COPY --from will just grab what exists.

# Public assets
COPY --from=builder /app/public ./public

# Standalone bundle (created when next.config.ts has output: 'standalone')
COPY --from=builder --chown=nextjs:nextjs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nextjs /app/.next/static ./.next/static

# ── Fallback: if standalone is NOT enabled, copy .next + node_modules ────────
# (Comment this block out if you set output:'standalone' in next.config.ts)
COPY --from=builder --chown=nextjs:nextjs /app/.next ./.next
COPY --from=deps    /app/node_modules ./node_modules
COPY --from=builder /app/package.json  ./package.json

RUN chown -R nextjs:nextjs /app

USER nextjs

# Next.js default port
EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Start using the standalone server if present, otherwise fall back to `next start`
CMD ["sh", "-c", "if [ -f server.js ]; then node server.js; else yarn start; fi"]
